-- Thai provinces reference table with bilingual names and regions
CREATE TABLE IF NOT EXISTS provinces (
  id INTEGER PRIMARY KEY,
  name_th TEXT NOT NULL UNIQUE,
  name_en TEXT NOT NULL,
  region TEXT NOT NULL
);

INSERT OR IGNORE INTO provinces (id, name_th, name_en, region) VALUES
-- Bangkok & Vicinity
(1, 'กรุงเทพมหานคร', 'Bangkok', 'Central'),
(2, 'นนทบุรี', 'Nonthaburi', 'Central'),
(3, 'ปทุมธานี', 'Pathum Thani', 'Central'),
(4, 'สมุทรปราการ', 'Samut Prakan', 'Central'),
(5, 'นครปฐม', 'Nakhon Pathom', 'Central'),
-- Central
(6, 'พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Central'),
(7, 'อ่างทอง', 'Ang Thong', 'Central'),
(8, 'ลพบุรี', 'Lopburi', 'Central'),
(9, 'สิงห์บุรี', 'Sing Buri', 'Central'),
(10, 'ชัยนาท', 'Chai Nat', 'Central'),
(11, 'สระบุรี', 'Saraburi', 'Central'),
(12, 'นครนายก', 'Nakhon Nayok', 'Central'),
(13, 'สมุทรสาคร', 'Samut Sakhon', 'Central'),
(14, 'สมุทรสงคราม', 'Samut Songkhram', 'Central'),
(15, 'สุพรรณบุรี', 'Suphan Buri', 'Central'),
(16, 'กาญจนบุรี', 'Kanchanaburi', 'Central'),
(17, 'ราชบุรี', 'Ratchaburi', 'Central'),
(18, 'เพชรบุรี', 'Phetchaburi', 'Central'),
(19, 'ประจวบคีรีขันธ์', 'Prachuap Khiri Khan', 'Central'),
-- East
(20, 'ชลบุรี', 'Chon Buri', 'East'),
(21, 'ระยอง', 'Rayong', 'East'),
(22, 'จันทบุรี', 'Chanthaburi', 'East'),
(23, 'ตราด', 'Trat', 'East'),
(24, 'ฉะเชิงเทรา', 'Chachoengsao', 'East'),
(25, 'ปราจีนบุรี', 'Prachin Buri', 'East'),
(26, 'สระแก้ว', 'Sa Kaeo', 'East'),
-- North
(27, 'เชียงใหม่', 'Chiang Mai', 'North'),
(28, 'เชียงราย', 'Chiang Rai', 'North'),
(29, 'ลำพูน', 'Lamphun', 'North'),
(30, 'ลำปาง', 'Lampang', 'North'),
(31, 'แม่ฮ่องสอน', 'Mae Hong Son', 'North'),
(32, 'แพร่', 'Phrae', 'North'),
(33, 'น่าน', 'Nan', 'North'),
(34, 'พะเยา', 'Phayao', 'North'),
(35, 'อุตรดิตถ์', 'Uttaradit', 'North'),
(36, 'ตาก', 'Tak', 'North'),
(37, 'สุโขทัย', 'Sukhothai', 'North'),
(38, 'พิษณุโลก', 'Phitsanulok', 'North'),
(39, 'พิจิตร', 'Phichit', 'North'),
(40, 'เพชรบูรณ์', 'Phetchabun', 'North'),
(41, 'กำแพงเพชร', 'Kamphaeng Phet', 'North'),
(42, 'นครสวรรค์', 'Nakhon Sawan', 'North'),
(43, 'อุทัยธานี', 'Uthai Thani', 'North'),
-- Northeast (Isan)
(44, 'นครราชสีมา', 'Nakhon Ratchasima', 'Northeast'),
(45, 'บุรีรัมย์', 'Buri Ram', 'Northeast'),
(46, 'สุรินทร์', 'Surin', 'Northeast'),
(47, 'ศรีสะเกษ', 'Si Sa Ket', 'Northeast'),
(48, 'อุบลราชธานี', 'Ubon Ratchathani', 'Northeast'),
(49, 'ยโสธร', 'Yasothon', 'Northeast'),
(50, 'อำนาจเจริญ', 'Amnat Charoen', 'Northeast'),
(51, 'ชัยภูมิ', 'Chaiyaphum', 'Northeast'),
(52, 'ขอนแก่น', 'Khon Kaen', 'Northeast'),
(53, 'อุดรธานี', 'Udon Thani', 'Northeast'),
(54, 'หนองคาย', 'Nong Khai', 'Northeast'),
(55, 'เลย', 'Loei', 'Northeast'),
(56, 'หนองบัวลำภู', 'Nong Bua Lam Phu', 'Northeast'),
(57, 'บึงกาฬ', 'Bueng Kan', 'Northeast'),
(58, 'สกลนคร', 'Sakon Nakhon', 'Northeast'),
(59, 'นครพนม', 'Nakhon Phanom', 'Northeast'),
(60, 'มุกดาหาร', 'Mukdahan', 'Northeast'),
(61, 'กาฬสินธุ์', 'Kalasin', 'Northeast'),
(62, 'ร้อยเอ็ด', 'Roi Et', 'Northeast'),
(63, 'มหาสารคาม', 'Maha Sarakham', 'Northeast'),
-- South
(64, 'นครศรีธรรมราช', 'Nakhon Si Thammarat', 'South'),
(65, 'สุราษฎร์ธานี', 'Surat Thani', 'South'),
(66, 'ชุมพร', 'Chumphon', 'South'),
(67, 'ระนอง', 'Ranong', 'South'),
(68, 'พังงา', 'Phang Nga', 'South'),
(69, 'ภูเก็ต', 'Phuket', 'South'),
(70, 'กระบี่', 'Krabi', 'South'),
(71, 'ตรัง', 'Trang', 'South'),
(72, 'พัทลุง', 'Phatthalung', 'South'),
(73, 'สงขลา', 'Songkhla', 'South'),
(74, 'สตูล', 'Satun', 'South'),
(75, 'ปัตตานี', 'Pattani', 'South'),
(76, 'ยะลา', 'Yala', 'South'),
(77, 'นราธิวาส', 'Narathiwat', 'South');
